### ISSUE TITLE
Server Lagg

### ISSUE THREAD

**Issue by antiker** [MistCore/MistCore#1] opened 2014-02-13 23:07 UTC
When I level and a new spell get laggy the server 5 -10 sec

The debug log says nothing about!

---

Small message from JunkyBulgaria:
The OBJECT_UPDATE system needs to be rewritten because on mana gain it leaks the network bandwidth of the host and takes 5-6mbps per 1 client.

**Comment by Dokman** [comment] 2014-02-14 16:25
yes like ever we need to modify the memory allocator i think

**Comment by Dokman** [comment] 2014-02-15 13:44
you need a good pc for run it without lag

**Comment by antiker** [comment] 2014-02-15 14:06
it is not on PC!
it lags yes only if you get a level up comes and it gets a new spell

With the version 5.1.0 it is not laggy

This is my Server:
AMD Opteron™, 8 Cores, 8x 2,3 GHz
32 GB DDR3-RAM
2x 3.000 GB SATA II-HDD; 7,2k

**Comment by Farbod** [comment] 2014-02-18 21:31
Yes it is true
I found that when you have 100% mana you won't get lag , but when your character has 1-99% mana you will get lag 100% lag.

/roll dosen't work
you won't sell items to npc

**Comment by Dokman** [comment] 2014-02-27 09:21
when  you levelup a char too i don't know what is the problem TT

**Comment by Dokman** [comment] 2014-03-03 18:38
anyone want's to help us?

**Comment by maxxx** [comment] 2014-03-04 09:22
lol. Problem in auto learning taxi paths, this code really sucks

**Comment by Dokman** [comment] 2014-03-04 10:23
Update: is not in worldserver.conf

Yes is code i don't know what

**Comment by Kittnz** [comment] 2014-03-04 21:11
About leveling up, i found out that when you level up, some VMAP's are loading and delays the levelup function to return. 
Log: http://paste2.org/yIsKmv0h

**Comment by Kittnz** [comment] 2014-03-04 22:18
Another update, vmaps is lagging the shit out of the server. Maybe we should try disabling vmaps and see how that works out.

**Comment by Dokman** [comment] 2014-03-04 22:23
or debugging it xD i don't know how but yes is the best thing that we can do

**Comment by Kittnz** [comment] 2014-03-05 12:24
Temp fix up, more research will get into this.

**Comment by lAminl** [comment] 2014-03-06 20:52
the problem isen't from taxi mods or opcode , it's from packet sizes , some byte buffers aren't converted to 5.0.5 still , and so not send and receive correction packets from client to server and return.
however already fixed this problem.

**Comment by Kittnz** [comment] 2014-03-06 21:18
@megatronir Would you like to share this with us? Also could this be the same issue with #15 ?
I'm still learning about this, it/you would be a great help.

**Comment by lAminl** [comment] 2014-03-07 14:48
add my skype id: stefan_world

**Comment by FALL1N1** [comment] 2014-03-22 21:44
Remove pandashan's stuff.

**Comment by FALL1N1** [comment] 2014-04-24 19:53
The OBJECT_UPDATE system needs to be rewritten because on mana gain it leaks the network bandwidth of the host and takes 5-6mbps per 1 client.

**Comment by Igorinus** [comment] 2014-04-26 13:24
if you guys whant to stop have latency then stop using  vs2012 or 2013 just 2010 i was  doing test and i can prove

**Comment by Kittnz** [comment] 2014-04-26 14:54
2010 x64? I haven't tried building it with 2010.

**Comment by UtilExe** [comment] 2014-04-26 17:12
if you compile with 2010 you will get quite many errors, so you need to compile with 12+ if you wanna "avoid" the errors.

**Comment by Farbod** [comment] 2014-04-27 12:24
tonight I will send pull req for fix lag problem and roll opcodes and sell items to vendor for you all :)

**Comment by caffeine239** [comment] 2014-04-28 23:43
i think i fixed but i need someone to test who gets this lag

**Comment by Kittnz** [comment] 2014-04-29 06:46
@caffeine239 i don't have a server with players running so i can't help. @silvermcd123 can help i think

**Comment by digz6666** [comment] 2014-04-29 06:53
@caffeine239 I have server running with this problem.

**Comment by caffeine239** [comment] 2014-04-29 10:52
@digz6666 add me to skype, Caffeine239

**Comment by digz6666** [comment] 2014-04-29 10:57
@caffeine239 Added

**Comment by caffeine239** [comment] 2014-04-30 01:55
Fixed in https://github.com/MistCore/MistCore/commit/02bf6e3df2d99533b47bbe1dd4121f82197fefaa
and https://github.com/MistCore/MistCore/commit/f758224dc54ec8af6531a9f2f1155e912ce2ccb0

**Closed as completed by caffeine239** 2014-04-30 01:55 UTC
Labels: Priority-Critical
